import { ACTION_PREFIX } from '../constants';

export const CREATE_USER_WITH_EMAIL_AND_PASSWORD = `${ACTION_PREFIX}CREATE_USER_WITH_EMAIL_AND_PASSWORD`;

export const SIGNIN_WITH_EMAIL_AND_PASSWORD = `${ACTION_PREFIX}SIGNIN_WITH_EMAIL_AND_PASSWORD`;
export const SIGNIN_ANONYMOUSLY = `${ACTION_PREFIX}SIGNIN_ANONYMOUSLY`;
export const SIGNIN_WITH_CUSTOM_TOKEN = `${ACTION_PREFIX}SIGNIN_WITH_CUSTOM_TOKEN`;

export const SIGNOUT = `${ACTION_PREFIX}SIGNOUT`;

export const AUTH_FAILURE = `${ACTION_PREFIX}AUTH_FAILURE`;
export const AUTH_CHANGED = `${ACTION_PREFIX}AUTH_CHANGED`;

export default {
  CREATE_USER_WITH_EMAIL_AND_PASSWORD,
  SIGNIN_WITH_EMAIL_AND_PASSWORD,
  SIGNIN_ANONYMOUSLY,
  SIGNIN_WITH_CUSTOM_TOKEN,
  SIGNOUT,
  AUTH_FAILURE,
  AUTH_CHANGED,
};
