import { ACTION_PREFIX } from '../constants';

export const CREATE_USER_WITH_EMAIL_AND_PASSWORD = `${ACTION_PREFIX}CREATE_USER_WITH_EMAIL_AND_PASSWORD`;

export const SIGNIN_WITH_EMAIL_AND_PASSWORD = `${ACTION_PREFIX}SIGNIN_WITH_EMAIL_AND_PASSWORD`;
export const SIGNIN_ANONYMOUSLY = `${ACTION_PREFIX}SIGNIN_ANONYMOUSLY`;
export const SIGNIN_WITH_GOOGLE = `${ACTION_PREFIX}SIGNIN_WITH_GOOGLE`;
export const SIGNIN_WITH_FACEBOOK = `${ACTION_PREFIX}SIGNIN_WITH_FACEBOOK`;
export const SIGNIN_WITH_TWITTER = `${ACTION_PREFIX}SIGNIN_WITH_TWITTER`;
export const SIGNIN_WITH_GITHUB = `${ACTION_PREFIX}SIGNIN_WITH_GITHUB`;

export const SIGNOUT = `${ACTION_PREFIX}SIGNOUT`;

export const AUTH_INIT = `${ACTION_PREFIX}AUTH_INIT`;
export const AUTH_FAILURE = `${ACTION_PREFIX}AUTH_FAILURE`;
export const AUTH_CHANGED = `${ACTION_PREFIX}AUTH_CHANGED`;

export default {
  AUTH_INIT,
  CREATE_USER_WITH_EMAIL_AND_PASSWORD,
  SIGNIN_WITH_EMAIL_AND_PASSWORD,
  SIGNIN_ANONYMOUSLY,
  SIGNIN_WITH_GOOGLE,
  SIGNIN_WITH_FACEBOOK,
  SIGNIN_WITH_TWITTER,
  SIGNIN_WITH_GITHUB,
  SIGNOUT,
  AUTH_FAILURE,
  AUTH_CHANGED,
};
